### ISSUE TITLE
New test organizations in COLIN - request to refresh Orgbook test

### ISSUE THREAD

**Issue by jonargue** [bcgov/orgbook-bc-client-angular#10]
Hi,

The following organizations have been incorporated in COLIN / Society Online test.
Can we please get test Orgbook refreshed so these new orgs show up?

This is to help the MOTI PTMP project with their testing.

SUPER TAXI INC. | BC0879696 | 999675606BC0001
ALIEN SPACE VENTURES LTD. | BC0879697 | 999679905BC0001
DISPLACEMENT TRUCKING LTD. | BC0879698 | 999679707BC0001
SMALL TOWN TRANSIT-YOU LTD. | BC0879699 | 999679509BC0001
WE-FIX-CARS LTD. | BC0879700 | 999679301BC0001
TAKE YOU ANYWHERE SOCIETY | S1001060 | 99967   5408 BC0001
CRAZY CAMPING TOURS SOCIETY | S1001061 | 99967   5200 BC0001

Cheers,

Jonathan

**Comment by swcurran** [comment]
Thanks -- over to you @ianco to add these.  NTH -- a brief readme in this repo of how to do this.

**Comment by ianco** [comment]
Completed - companies are now available in orgbook test

**Comment by ianco** [comment]
> ... a brief readme in this repo of how to do this.

FYI The admin scripts are located here:  https://github.com/bcgov/von-bc-registries-agent-configurations

There are corresponding scripts here (in case there is any orgbook cleanup required as part of processing or re-processing):  https://github.com/bcgov/orgbook-configurations

**Comment by jonargue** [comment]
Thanks everyone - much appreciated!
