### ISSUE TITLE
New test organizations in COLIN

### ISSUE THREAD

**Issue by jonargue** [bcgov/orgbook-bc-client-angular#12]
Hi,

The following organizations have been incorporated in COLIN test.
Can we please get test Orgbook refreshed so these new orgs show up?

This is to help the MOTI PTMP project with their testing.

ELITE MANAGEMENT CONSULTING INC., BC0879745
EWING TRANSPORT INC., BC0879748
AUDIT FUEL HAULERS LTD., BC0879749

thanks!

**Comment by swcurran** [comment]
@amanji -- can you do this?  If not @ianco can help you with it, so you know how.

Thanks

**Comment by ianco** [comment]
Adding to the ticket for posterity:

You need this repo: https://github.com/bcgov/von-bc-registries-agent-configurations

… and then you run `./manage -e test queueOrganization S1001061` (or whatever the org is)

(for `BC...` orgs you just use the number, e.g for `BC0879745` you use `./manage -e test queueOrganization 0879745`)

(for other orgs you just use the full number)

… and then you kick off the job to process the credentials

I usually do this as:

`oc rsh event-processor-indy-cat-45-cjmf2` to rsh into the appropriate container (use the appropriate container name in `test` obvs)

… and then:

```
cd scripts
# display the status (should show the number of outstanding orgs to process)
./run-step.sh bcreg/display_pipeline_status.py
# this generates and "stages" the credentials
./run-step.sh bcreg/process-corps-generate-creds.py
# posts the credentials to orgbook
./run-step.sh bcreg/display_pipeline_status.py
```

**Comment by amanji** [comment]
These should now be online
