### ISSUE TITLE
New test organizations

### ISSUE THREAD

**Issue by jonargue** [bcgov/orgbook-bc-client-angular#16]
Hi,

I've got some more test organizations which need to be added to Orgbook

MORRIS MOVING LTD. | BC0879841, BN: 999430606BC0001
ROAD RUNNER TAXI LTD. | BC0879840, BN: 999442502BC0001
BUGSY INSPECTIONS LTD. | BC0879839, BN: 999430804BC0001
TAZMANIAN DEVIL CARRIERS LTD. | BC0879838, BN: 999431000BC0001
YOSEMITE SAM FIXERS LTD. | BC0879837, BN: 999431208BC0001
MARTIAN TRAVEL LTD. | BC0879836, BN: 999442700BC0001
KATALON CARRIERS INC. | BC0879833, BN: 999450901BC0001
KATALON INSPECTIONS INC. | BC0879834, BN: 999438807BC0001
KATALON TAXI | BN # 99943 8609 BC0001, Registration # FM1006106

Thanks!

**Comment by swcurran** [comment]
Over to you @amanji .  Thanks!

**Comment by amanji** [comment]
These should now be searchable at `test.orgbook.gov.bc.ca`
