### ISSUE TITLE
New test companies to be added to test orgbook

### ISSUE THREAD

**Issue by jonargue** [bcgov/orgbook-bc-client-angular#19]
Hi,

Can the following companies please be added to orgbook in test?

O'SWIFT TRANSPORTATION INC. | BC0880209  BN: 999376205BC0001
-- | --
BINO'S BUS SALES LTD. | BC0880210  BN: 999376007BC0001
THE GREATEST CARRIER IN THE WORLD LTD. | BC0880211  BN: 999388309BC0001
ICBC-TESTING SUSPENDED CARRIER LTD. | BC0880212  BN: 999375801BC0001

**Comment by swcurran** [comment]
Over to you @amanji ! :-)

**Comment by amanji** [comment]
I have attempted to queue these Organizations however they are not being indexed in https://test.orgbook.gov.bc.ca. Have the credentials been posted?

**Comment by amanji** [comment]
Update:

Only `BINO'S BUS SALES LTD.` and `ICBC-TESTING SUSPENDED CARRIER LTD.` have been indexed

**Comment by WadeBarnes** [comment]
@amanji, the other 2 companies are showing up as archived.  They appear when you check the `Show Archived` option.

**Comment by amanji** [comment]
Excellent. Will close then.
