### ISSUE TITLE
Column sorting in credentials timeline panel is not working

### ISSUE THREAD

**Issue by alexgmetcalf** [bcgov/orgbook-bc-client-angular#22]
On a credential detail page, if you switch the timeline view of credentials at the bottom of the page from date view to list view, then clicking on any of the headings to sort by other criteria doesn’t work, and instead links back to the homepage.
<img width="700" alt="image" src="https://user-images.githubusercontent.com/75134312/107699829-7d096400-6c6b-11eb-921b-2b9721f054be.png">

**Comment by amanji** [comment]
Will be fixed as part of the UI re-write.
