### ISSUE TITLE
verifiable is spelled wrong in your About Us content

### ISSUE THREAD

**Issue by swcurran** [bcgov/orgbook-bc-client-angular#32]
Ouch.  :-)

Please fix and spell check the rest of the content, just in case.

Assigning to @wadeking98 -- ask @amanji for how to PR, push to be promoted and tested.

Thanks!

**Comment by WadeBarnes** [comment]
Addressed in [Release 1.0.3](https://github.com/bcgov/orgbook-bc-client/releases/1.0.3).  Deployed to `prod`; https://orgbook.gov.bc.ca/
