### ISSUE TITLE
Companies to be entered into Orgbook Test

### ISSUE THREAD

**Issue by jonargue** [bcgov/orgbook-bc-client-angular#35]
Hi,
Can you please add the following companies to Orgbook test?
thx

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/jonat/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/jonat/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

BETA AVIATION INC. | NR   5806591
-- | --
Incorporation Number: BC 0886270
Business Number: 994926301BC0001
  |  
  |  
WHIRLPOOL   NAVIGATIONS LTD. | NR 1614921
Incorporation Number: BC 0886271
Business Number: 994926103BC0001
  |  
  |  
GORILLAMASTER   AUTOMOTIVE INC. | NR 1917610
 
Incorporation Number: BC 0886272
Business Number: 994925907BC0001
  |  
  |  
VOIDMART CARRIERS   INC. | NR 9972126
Incorporation Number: BC 0886273
Business Number: 994925709BC0001
  |  
  |  
CAVESEARCH   INVESTIGATIONS LTD. | NR 7285002
Incorporation Number: BC 0886278
Business Number: 994878403BC0001
  |  
  |  
MINION NETWORKS LTD. | NR 1130299
Incorporation Number: BC 0886280
Business Number: 994925501BC0001
  |  
  |  
TITAN MOTORS INC. | NR 8511176
Incorporation Number: BC 0886281
Business Number: 994925303BC0001
  |  
  |  
PTM SYSTEM LOAD TESTING INC. | NR 6537920
Incorporation Number: BC 0886282
Business Number: 994925105BC0001

</body>

</html>

**Comment by ianco** [comment]
@jonargue  these companies have been loaded into Orgbook test:  https://test.orgbook.gov.bc.ca/en/home

**Comment by swcurran** [comment]
Didn't see any feedback, but @jonargue , I assume you are good with this.  Please reopen if not.
