### ISSUE TITLE
Need company to appear in Org Book test 

### ISSUE THREAD

**Issue by afillier** [bcgov/orgbook-bc-client-angular#37]
Name: 	TRUCKING BUZZ CARRIERS INC.
Corp#:  BC0908521
Could this company please be added to Orgbook test? 

Thank you! 
Alanna

**Comment by ianco** [comment]
This company is now available in OrgBook test:

https://test.orgbook.gov.bc.ca/en/organization/registration.registries.ca/BC0908521

**Comment by afillier** [comment]
Thank you 😊
