### ISSUE TITLE
Look-ahead search feature suggests multiple identical search strings

### ISSUE THREAD

**Issue by alexgmetcalf** [bcgov/orgbook-bc-client-angular#7]
On the live OrgBook BC service, if you start typing a search string such as "Telus Communications", the look-ahead search feature suggests multiple auto-completions that are identical.

<img width="567" alt="image" src="https://user-images.githubusercontent.com/75134312/108241843-1d92d480-7101-11eb-978a-79c0b8f96d34.png">

**Comment by amanji** [comment]
Do we want to apply this fix to Aries-VCR and Orgbook-ON as well? Should Aries-VCR have the filters applied at all?

**Comment by swcurran** [comment]
I think all three, please.

Will the filtering before or after paging?  E.g. if the front end requests a page with 20 results, will it get the 20 after the filtering?

**Comment by amanji** [comment]
The results won't affect paging. The parameters are applied to the Solr query so no post-processing is required.

**Comment by amanji** [comment]
Need to update the query to exclude revoked results in both autocomplete and search results.
